model:
  input_size: 448  # 256
  flow_steps: 4
  backbone: "mcait"  # resnet18, wide_resnet50_2
trainer:
  epochs: 200
  batch_train: 13
  batch_val: 5
  learning_rate: 3.163419554150971e-5
  weight_decay: 1e-5
  log_every_n_epochs: 1
  save_ckpt_every: 25
  save_debug_images_every: 25
  log_predefined_debug_images: true
  log_n_images: 20  # if not log_predefined_debug_images, or images not available
